export const overdueAlertTemplate = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      background-color: #f4f6f8;
      color: #333333;
      margin: 0;
      padding: 0;
      line-height: 1.6;
    }
    .wrapper {
      padding: 0;
      background-color: #f4f6f8;
    }
    .container {
      width: 100%;
      margin: 0 auto;
      background-color: #ffffff;
      border-radius: 8px;
      overflow: hidden;
      box-shadow: 0 4px 15px rgba(0, 0, 0, 0.05);
    }
    .header {
      background: linear-gradient(135deg, #e53935, #c62828);
      color: #ffffff;
      padding: 25px 30px;
      text-align: center;
    }
    .header h2 {
      margin: 0;
      font-size: 24px;
      font-weight: 600;
      letter-spacing: 0.5px;
    }
    .header .icon {
      font-size: 32px;
      margin-bottom: 10px;
      display: inline-block;
    }
    .content {
      padding: 20px;
    }
    .content p {
      margin: 0 0 20px 0;
      font-size: 16px;
      color: #555555;
    }
    .highlight-date {
      font-weight: 700;
      color: #c62828;
    }
    .table-container {
      margin: 25px 0;
      border-radius: 6px;
      overflow: hidden;
      border: 1px solid #e0e0e0;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      background-color: #ffffff;
    }
    th, td {
      padding: 14px 18px;
      text-align: left;
      border-bottom: 1px solid #eeeeee;
    }
    th {
      background-color: #f8f9fa;
      font-weight: 600;
      color: #444444;
      font-size: 13px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    tr:last-child td {
      border-bottom: none;
    }
    tr:nth-child(even) {
      background-color: #fafafa;
    }
    .part-no {
      font-weight: 700;
      color: #1e293b;
    }
    .badge {
      display: inline-block;
      background-color: #fee2e2;
      color: #b91c1c;
      padding: 4px 10px;
      border-radius: 4px;
      font-size: 13px;
      font-weight: 600;
      border: 1px solid #fca5a5;
    }
    .action-container {
      text-align: center;
      margin-top: 35px;
      margin-bottom: 15px;
    }
    .btn {
      display: inline-block;
      background-color: #2563eb;
      color: #ffffff;
      text-decoration: none;
      padding: 14px 28px;
      border-radius: 6px;
      font-weight: 600;
      font-size: 16px;
      box-shadow: 0 2px 4px rgba(37, 99, 235, 0.3);
    }
    .footer {
      background-color: #f8f9fa;
      padding: 20px;
      text-align: center;
      border-top: 1px solid #eeeeee;
    }
    .footer p {
      margin: 0;
      font-size: 13px;
      color: #888888;
    }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="container">
      <div class="header">
        <div class="icon">⚠️</div>
        <h2>Action Required: Overdue Reports</h2>
      </div>
      
      <div class="content">
        <p>Hello Team,</p>
        <p>Our daily check indicates that the following production parts do not have completed reports for today (<span class="highlight-date">{{date}}</span>).</p>
        
        <div class="table-container">
          <table>
            <thead>
              <tr>
                <th>Part Number</th>
                <th>Part Name</th>
                <th>Missing Requirement</th>
              </tr>
            </thead>
            <tbody>
              {{#each alerts}}
              <tr>
                <td class="part-no">{{partNumber}}</td>
                <td>{{partName}}</td>
                <td><span class="badge">{{missingType}}</span></td>
              </tr>
              {{/each}}
            </tbody>
          </table>
        </div>
        
        <p>To maintain compliance, please log in to the IRMS dashboard and submit these pending reports immediately.</p>
      </div>
      
      <div class="footer">
        <p>This is an automated alert generated by the IRMS Quality Management System. Please do not reply to this email.</p>
      </div>
    </div>
  </div>
</body>
</html>`;
